-- MEU Atlas - date initiale
-- Ruleaza in Supabase > SQL Editor dupa ce schema exista.

insert into public.members (id, name, email, department, primary_role, manager, access_level, safe_person, status)
values
  ('MEM-0001', 'Viorel Lambu', 'viorel.lambu@meu-atlas.local', 'Executiv & Tehnologie', 'Director General', null, 'Director', false, 'Activ'),
  ('MEM-0002', 'Paula Iovescu', 'paula.iovescu@meu-atlas.local', 'Executiv & Tehnologie', 'Director General Adjunct', 'Viorel Lambu', 'Director', false, 'Activ'),
  ('MEM-0003', 'Marina Petrescu', 'marina.petrescu@meu-atlas.local', 'Executiv & Tehnologie', 'Project Manager 1 - External Affairs', 'Viorel Lambu', 'Manager', false, 'Activ'),
  ('MEM-0004', 'Maysa Coman', 'maysa.coman@meu-atlas.local', 'Executiv & Tehnologie', 'Project Manager 2 - Operations', 'Viorel Lambu', 'Manager', false, 'Activ'),
  ('MEM-0005', 'Andrei Tufis', 'andrei.tufis@meu-atlas.local', 'Executiv & Tehnologie', 'Chief Technology Officer', 'Viorel Lambu', 'Admin', true, 'Activ'),
  ('MEM-0006', 'Rares Craciun', 'rares.craciun@meu-atlas.local', 'Logistica', 'Head of Mobility & Accommodation', 'Maysa Coman', 'Coordonator', false, 'Activ'),
  ('MEM-0007', 'Tatiana Gulca', 'tatiana.gulca@meu-atlas.local', 'Logistica', 'Head of Event Production', 'Maysa Coman', 'Coordonator', false, 'Activ'),
  ('MEM-0008', 'Patricia Dumitrean', 'patricia.dumitrean@meu-atlas.local', 'Logistica', 'Head of Venues & Hospitality', 'Maysa Coman', 'Coordonator', false, 'Activ'),
  ('MEM-0009', 'Dariana Iovicescu', 'dariana.iovicescu@meu-atlas.local', 'Logistica', 'Head of Production & Materials', 'Maysa Coman', 'Coordonator', true, 'Activ'),
  ('MEM-0010', 'Danu Plamadeala', 'danu.plamadeala@meu-atlas.local', 'Logistica', 'Head of Protocol & Ceremonial Affairs', 'Maysa Coman', 'Coordonator', false, 'Activ'),
  ('MEM-0011', 'Raluca Panainte', 'raluca.panainte@meu-atlas.local', 'Resurse Umane', 'Director of Human Resources', 'Viorel Lambu', 'Director', false, 'Activ'),
  ('MEM-0012', 'Cristian Mocuta', 'cristian.mocuta@meu-atlas.local', 'Resurse Umane', 'Head of Simulation Programme', 'Raluca Panainte', 'Coordonator', false, 'Activ'),
  ('MEM-0013', 'Darius Shahheydari', 'darius.shahheydari@meu-atlas.local', 'Resurse Umane', 'Head of Recruitment & Selection', 'Raluca Panainte', 'Coordonator', false, 'Activ'),
  ('MEM-0014', 'Andreea Potorac', 'andreea.potorac@meu-atlas.local', 'Resurse Umane', 'Head of Participants', 'Raluca Panainte', 'Coordonator', false, 'Activ'),
  ('MEM-0015', 'Luca Ciubotaru', 'luca.ciubotaru@meu-atlas.local', 'Resurse Umane', 'Head of Wellbeing & Internal Culture', 'Raluca Panainte', 'Coordonator', true, 'Activ'),
  ('MEM-0016', 'Karina Lupas', 'karina.lupas@meu-atlas.local', 'Resurse Umane', 'Head of Risk & Safety Management', 'Raluca Panainte', 'Coordonator', false, 'Activ'),
  ('MEM-0017', 'Raluca Ciucurita', 'raluca.ciucurita@meu-atlas.local', 'Resurse Umane', 'Head of Legal Affairs & Compliance', 'Raluca Panainte', 'Coordonator', false, 'Activ'),
  ('MEM-0018', 'Alessia Caragea', 'alessia.caragea@meu-atlas.local', 'Comunicare', 'Director of Communication, Image & Institutional Marketing', 'Viorel Lambu', 'Director', false, 'Activ'),
  ('MEM-0019', 'George Ropota', 'george.ropota@meu-atlas.local', 'Comunicare', 'Head of Communications & Public Affairs', 'Alessia Caragea', 'Coordonator', false, 'Activ'),
  ('MEM-0020', 'Nicoleta Voina', 'nicoleta.voina@meu-atlas.local', 'Comunicare', 'Head of Social Media & Digital Strategy', 'Alessia Caragea', 'Coordonator', false, 'Activ'),
  ('MEM-0021', 'Cristiana Ozon', 'cristiana.ozon@meu-atlas.local', 'Fundraising & Parteneriate', 'Director of Fundraising & Partnerships', 'Viorel Lambu', 'Director', false, 'Activ'),
  ('MEM-0022', 'Alexia Rain', 'alexia.rain@meu-atlas.local', 'Fundraising & Parteneriate', 'Asistent Manager', 'Cristiana Ozon', 'Coordonator', false, 'Activ')
on conflict (id) do update set
  name = excluded.name,
  email = excluded.email,
  department = excluded.department,
  primary_role = excluded.primary_role,
  manager = excluded.manager,
  access_level = excluded.access_level,
  safe_person = excluded.safe_person,
  status = excluded.status;

insert into public.role_assignments (department, title, member_id, safe_person, status)
values
  ('Executiv & Tehnologie', 'Director General', 'MEM-0001', false, 'Ocupat'),
  ('Executiv & Tehnologie', 'Director General Adjunct', 'MEM-0002', false, 'Ocupat'),
  ('Executiv & Tehnologie', 'Project Manager 1 - External Affairs', 'MEM-0003', false, 'Ocupat'),
  ('Executiv & Tehnologie', 'Project Manager 2 - Operations', 'MEM-0004', false, 'Ocupat'),
  ('Executiv & Tehnologie', 'Chief Technology Officer', 'MEM-0005', true, 'Ocupat'),
  ('Logistica', 'Director of Logistics', null, false, 'Neocupat'),
  ('Logistica', 'Head of Mobility & Accommodation', 'MEM-0006', false, 'Ocupat'),
  ('Logistica', 'Head of Event Production', 'MEM-0007', false, 'Ocupat'),
  ('Logistica', 'Head of Venues & Hospitality', 'MEM-0008', false, 'Ocupat'),
  ('Logistica', 'Head of Production & Materials', 'MEM-0009', true, 'Ocupat'),
  ('Logistica', 'Head of Protocol & Ceremonial Affairs', 'MEM-0010', false, 'Ocupat'),
  ('Resurse Umane', 'Director of Human Resources', 'MEM-0011', false, 'Ocupat'),
  ('Resurse Umane', 'Head of Simulation Programme', 'MEM-0012', false, 'Ocupat'),
  ('Resurse Umane', 'Head of Recruitment & Selection', 'MEM-0013', false, 'Ocupat'),
  ('Resurse Umane', 'Head of Participants', 'MEM-0014', false, 'Ocupat'),
  ('Resurse Umane', 'Director HR - suport participanti', 'MEM-0011', false, 'Ocupat'),
  ('Resurse Umane', 'Head of Wellbeing & Internal Culture', 'MEM-0015', true, 'Ocupat'),
  ('Resurse Umane', 'Head of Risk & Safety Management', 'MEM-0016', false, 'Ocupat'),
  ('Resurse Umane', 'Head of Legal Affairs & Compliance', 'MEM-0017', false, 'Ocupat'),
  ('Comunicare', 'Director of Communication, Image & Institutional Marketing', 'MEM-0018', false, 'Ocupat'),
  ('Comunicare', 'Head of Communications & Public Affairs', 'MEM-0019', false, 'Ocupat'),
  ('Comunicare', 'Head of Social Media & Digital Strategy', 'MEM-0020', false, 'Ocupat'),
  ('Comunicare', 'Head of Brand & Visual Identity', null, false, 'Neocupat'),
  ('Comunicare', 'Head of Visual Storytelling', 'MEM-0019', false, 'Ocupat'),
  ('Suport Institutional', 'Head of EU Institutional Affairs', 'MEM-0001', false, 'Ocupat'),
  ('Suport Institutional', 'Head of Academic Affairs', 'MEM-0005', true, 'Ocupat'),
  ('Fundraising & Parteneriate', 'Director of Fundraising & Partnerships', 'MEM-0021', false, 'Ocupat'),
  ('Fundraising & Parteneriate', 'Asistent Manager', 'MEM-0022', false, 'Ocupat'),
  ('Fundraising & Parteneriate', 'Head of Corporate Sponsorships', 'MEM-0001', false, 'Ocupat'),
  ('Fundraising & Parteneriate', 'Head of EU & Institutional Grants', 'MEM-0001', false, 'Ocupat'),
  ('Fundraising & Parteneriate', 'Head of Alumni & Donor Relations', 'MEM-0001', false, 'Ocupat');
